#!/bin/sh

jargs=4
for arg
do
    case "$arg" in
#    -noisy) jargs="$jargs -DPrecisionRuntime=enerj.rt.PrecisionRuntimeNoisy" ;;
    -noisy) jargs="$jargs $arg";; 
     *) 	echo $jargs;;
    esac
done

#command="java -DPrecisionRuntime=enerj.rt.PrecisionRuntimeNoisy  -Xbootclasspath/a:$jsr308jar:$cfrtjar:$enerjjar:$plumejar:$commonjar:$junitjar:. org.junit.runner.JUnitCore  $jargs"
#command="java -Xbootclasspath/a:$jsr308jar:$cfrtjar:$enerjjar:$plumejar $jargs"
#command="java -Xbootclasspath/a:$jsr308jar:$cfrtjar:$enerjjar:$plumejar:target/classes:target/test-classes:/dcsdata/home/hdokani2/.m2/repository/junit/junit/4.11/junit-4.11.jar:/dcsdata/home/hdokani2/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar org.junit.runner.JUnitCore $jargs"
#exec $command
